# Stats 21 - HW 3

Homework copyright Miles Chen. Problems have been adapted from teh exercises in Think Python 2nd Ed by Allen B. Downey.

The questions have been entered into this document. You will modify the document by entering your code.

Make sure you run the cell so the requested output is visible. Download the finished document as a PDF file. If you are unable to convert it to a PDF, you can download it as an HTML file and then print to PDF.

**Homework is an opportunity to practice coding and to practice problem solving. Doing exercises is where you will do most of your learning.**

**Copying someone else's solutions takes away your learning opportunities. It is also academic dishonesty.**

## Reading

- Chapters 11, 12, and 14

Please keep up with the reading. The chapters are short.

### Exercise 11.1

Write a function that reads the words in `words.txt` and stores them as keys in a dictionary. It doesn't matter what the values are. Then you can use the in operator as a fast way to
check whether a string is in the dictionary.

Use the same `words.txt` file from HW2.

Do Exercise 10.10 but this time searching the dictionary using the `in` operator. You can see how much faster it is to search a dictionary.

In [115]:
def make_word_dict():
    file = open('words.txt', 'r')
    words = dict()
    for word in file:
        words[word.strip()] = True
    return words

In [116]:
word_dict = make_word_dict()

In [117]:
"hello" in word_dict

True

### Exercise 11.4

In Exercise 10.7, you created a function called `has_duplicates()`. It takes a list as a parameter and returns `True` if there is any object that appears more than once in the list.

Use a dictionary to write a faster, simpler version of `has_duplicates()`.

In [118]:
def has_duplicates(t):
    count = dict()
    for item in t:
        if item in count:
            return True
        count[item] = 1
    return False

In [119]:
has_duplicates(['a','b','b','c'])

True

In [122]:
has_duplicates(['a','b','b','c'])

True

In [120]:
has_duplicates(['a','b','c','a'])

True

### Exercise 11.5

A Caesar cipher is a weak form of encryption that involves 'rotating' each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary. "A" rotated by 3 is "D". "Z" rotated by 1 is "A".

Two words are "rotate pairs" if you can rotate one of them and get the other. For example, "cheer" rotated by 7 is "jolly".

Write a script that reads in the wordlist `words.txt` and finds all the rotate pairs of words that are 5 letters or longer.

One function that could be helpful is the function `ord()` which converts a character to a numeric code. Keep in mind that numeric codes for uppercase and lowercase letters are different.

Some hints:

- you can write helper functions, such as a function that will rotate a letter by a certain number and/or another function that will rotate a word by a number of letters
- to keep your script running quickly, you should use the wordlist dictionary from exercise 11.1

In [121]:
# write your code here.
alphabet = list('abcdefghijklmnopqrstuvwxyz')


def rotate(s, n):
    word = ''
    for c in s:
        word += alphabet[(ord(c) - 97 + n) % 26]
    return word


file = open('words.txt', 'r')
word_dict_5 = dict()
for word in file:
    if len(word.strip()) >= 5:
        word_dict_5[word.strip()] = True

        
def find_rotate_pairs():
    for word in word_dict_5:
        for i in range(1, 26):
            if rotate(word, i) in word_dict_5:
                print(word + " +" + str(i) + " => " + rotate(word, i))
    pass


find_rotate_pairs()

abjurer +13 => nowhere
adder +1 => beefs
ahull +6 => gnarr
alkyd +4 => epoch
alula +19 => tenet
ambit +18 => setal
anteed +1 => bouffe
aptly +19 => timer
arena +17 => river
baiza +18 => tsars
banjo +4 => ferns
beefs +25 => adder
benni +16 => ruddy
biffs +6 => holly
bolls +6 => hurry
bombyx +6 => hushed
bouffe +25 => anteed
bourg +20 => viola
buffi +6 => hallo
bulls +6 => harry
bunny +17 => sleep
butyl +6 => hazer
chain +6 => ingot
cheer +7 => jolly
clasp +15 => raphe
cogon +16 => sewed
commy +16 => secco
corky +20 => wiles
craal +13 => penny
credo +16 => shute
creel +13 => perry
cubed +10 => melon
curly +20 => wolfs
cushy +20 => wombs
danio +4 => herms
dated +15 => spits
dawted +15 => splits
dazed +15 => spots
didos +12 => pupae
dolls +19 => wheel
drips +11 => octad
ebony +16 => uredo
eches +6 => kinky
epoch +22 => alkyd
fadge +14 => torus
fagot +14 => touch
ferns +22 => banjo
fills +6 => lorry
fizzy +5 => kneed
frena +17 => wiver
frere +13 => serer
fusion +6 => layout
ganja +4 => kern

### Exercise 12.2

Write a program that reads a word list from a file (see Section 9.1) and finds all the sets of words that are anagrams.

After finding all anagram sets, print the list of all anagram sets that have 6 or more entries in it.

Here is an example of what the output might look like:

~~~
['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
...
~~~

Hint:

First traverse the entire wordlist to build a dictionary that maps from a collection of letters to a list of words that can be spelled with those letters. The question is, how can you represent the collection of letters in a way that can be used as a key? i.e. The word "eat" and the word "tea" should be in a list associated with a key ('a','e','t').

In [149]:
fin = open("words.txt")
word_list = []
for line in fin:
    word_list.append(line.strip())
anagrams = dict()
for word in word_list:
    letters = list(word)
    letters.sort()
    s_letters = str(letters)
    if s_letters in anagrams:
        anagrams[s_letters].append(word)
    else:
        anagrams[s_letters] = [word]
for anagram in anagrams:
    if len(anagrams[anagram]) >= 6:
        print(anagrams[anagram])

['abets', 'baste', 'bates', 'beast', 'beats', 'betas', 'tabes']
['acers', 'acres', 'cares', 'carse', 'escar', 'races', 'scare', 'serac']
['acred', 'arced', 'cadre', 'cared', 'cedar', 'raced']
['aiders', 'deairs', 'irades', 'raised', 'redias', 'resaid']
['airts', 'astir', 'sitar', 'stair', 'stria', 'tarsi']
['alert', 'alter', 'artel', 'later', 'ratel', 'taler']
['alerting', 'altering', 'integral', 'relating', 'tanglier', 'triangle']
['alerts', 'alters', 'artels', 'estral', 'laster', 'ratels', 'salter', 'slater', 'staler', 'stelar', 'talers']
['alevin', 'alvine', 'valine', 'veinal', 'venial', 'vineal']
['algins', 'aligns', 'lasing', 'liangs', 'ligans', 'lingas', 'signal']
['aliens', 'alines', 'elains', 'lianes', 'saline', 'silane']
['aligners', 'engrails', 'nargiles', 'realigns', 'signaler', 'slangier']
['amens', 'manes', 'manse', 'means', 'mensa', 'names', 'nemas']
['anestri', 'nastier', 'ratines', 'retains', 'retinas', 'retsina', 'stainer', 'stearin']
['angriest', 'astringe', 'ganister

### NumPy Exercises

For the following exercises, be sure to print the desired output. You will not receive credit for problems that do not print the desired output.

Some of these exercises will require the use of functions in numpy that may not have been covered in class. Look up documentation on how to use them. I always recommend checking the official reference at https://numpy.org/doc/stable/reference/index.html 

In [151]:
import numpy as np
np.random.seed(1)

#### Exercise NP.1:

Task: Create an array `b` of 10 random integers selected between 0-99

Desired output: `[37 12 72  9 75  5 79 64 16  1]` of course yours might be different

In [170]:
b = np.random.randint(100, size=10)
print(b)

[43  6 77 56 59 15 24  9 66 71]


#### NP.1b:

Task: reverse the elements in `b`. Hint: Try slicing the array, but backwards

Desired output: `[ 1 16 64 79  5 75  9 72 12 37]` yours will be different

In [171]:
print(b[::-1])

[71 66  9 24 15 59 56 77  6 43]


#### NP.2a:

Task: Create an array `c` of 1000 random values selected from a normal distribution centered at 100 with sd = 15, rounded to 1 decimal place. Print only the first 10 values.

Desired output: `[ 92.1  83.9 113.   65.5 126.2  88.6 104.8  96.3 121.9  69.1]` of course your values may be different

In [188]:
c = np.random.normal(100, 15, 1000)
print(c[:10])

[108.709062   101.94109683 102.77589125 107.47815927  69.95546175
  85.92025879  98.14405543 111.25383127 110.01464298  95.18672591]


#### NP.2b:

Perform a Shapiro-Wilk test to see if the values in c come from a normal distribution. Report the p-value and appropriate conclusion.

Look up `scipy.stats.shapiro` for usage and details.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html

In [181]:
from scipy import stats
res = stats.shapiro(c)
print("p-value: " + str(res.pvalue))
print("conclusion: " + str(res.statistic))

p-value: 0.5166806578636169
conclusion: 0.9984409809112549


#### NP.2c:

Identify and print the values in `c` that are more than 3 standard deviations from the mean of `c`. Report the proportion of values that are more than 3 sd from the mean.

Desired output: `[ 54.1 ... 148.3 ]`

`0.32 of the values are beyond 3 sd from the mean.`

In [199]:
out = abs(((c - np.mean(c)) / np.std(c))) > 3
print(c[out])
print(str(np.sum(out) / len(c)) + " of the values are beyond 3 sd from the mean.")

[ 47.87234658  51.3492552   54.78925462 144.51708879]
0.004 of the values are beyond 3 sd from the mean.


#### NP.3:

Task: Make a 3x3 identity matrix called `I3`

Desired output: 

~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
~~~

In [208]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### NP.4a:

Task: Make a 10x10 array of values 1 to 100. Call it X

Desired output: 

~~~
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
 ~~~

In [207]:
X = np.reshape(range(1, 101), (10, 10))
print(X)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


#### NP.4b:

Task: Make a copy of X, call it Y (1 line). Replace all values in Y that are not squares with 0 (1 line). see `numpy.isin()`

Desired output: 

~~~
[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
...
 [  0   0   0   0   0   0   0   0   0 100]]
 ~~~

In [213]:
Y = X.copy()
Y = Y * np.isin(Y, [1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
print(Y)

[[  1   0   0   4   0   0   0   0   9   0]
 [  0   0   0   0   0  16   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0   0   0  49   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 100]]


#### NP.5:

Task: Use `np.tile()` to tile a 2x2 diagonal matrix of integers to make a checkerboard pattern. Call the matrix `checkers`

Desired output: 

~~~
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
 ~~~

In [216]:
print(np.tile(np.reshape([1, 0, 0, 1], (2, 2)), (4, 4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### NP.6:

Task: convert the values in `f_temp` from Farenheit to celsius. The conversion is subtract 32, then multiply by 5/9. Round to 1 decimal place.

Desired output: 

~~~
[[21.1 21.7 22.2 22.8 23.3 23.9]
 ...
 [34.4 35.  35.6 36.1 36.7 37.2]]
~~~

In [265]:
# do not modify
f_temp  = np.arange(70,100).reshape((5,6))

In [266]:
print(np.round((f_temp - 32) * 5 / 9, 1))

[[21.1 21.7 22.2 22.8 23.3 23.9]
 [24.4 25.  25.6 26.1 26.7 27.2]
 [27.8 28.3 28.9 29.4 30.  30.6]
 [31.1 31.7 32.2 32.8 33.3 33.9]
 [34.4 35.  35.6 36.1 36.7 37.2]]


#### NP.7:

Task: Convert values in the matrix `x` into z-scores by column, call it matrix `z`. That is: each column should have a mean of 0 and std of 1. (subtract the column mean, and divide by the column std). (not required, but see if you can do this in one line)

Print the column means and column std to show that they have been standardized.

Desired output: 

~~~
[[-1.09996745 -0.47901666  0.8816739 ]
 [ 0.9495002   1.18844641  0.11324252]
...
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]
 
 [ 6.66133815e-17  1.11022302e-16 -1.11022302e-16]
[1. 1. 1.]
~~~

In [255]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 30).reshape(10,3)

In [256]:
z = ((x - np.mean(x, axis = 0)) / np.std(x, axis = 0))
print(z)

[[-1.09996745 -0.47901666  0.8816739 ]
 [ 0.9495002   1.18844641  0.11324252]
 [-1.04808219  1.64320907  0.27501755]
 [ 1.23486912  0.40019114  0.84123014]
 [ 1.23486912 -0.78219177 -0.45297008]
 [-0.68488539 -0.75187426  0.5985676 ]
 [ 0.19716398 -0.72155675 -1.46406399]
 [ 1.10515598  1.40066898 -1.74717029]
 [-0.60705751 -1.08536687 -0.57430135]
 [-1.28156585 -0.81250928  1.52877401]]


In [258]:
print(np.mean(z, axis = 0))
print(np.std(z, axis = 0))

[ 4.44089210e-17  1.11022302e-16 -1.11022302e-16]
[1. 1. 1.]


#### NP.8:

Task: Convert values in the matrix `x` into scaled values from 0 to 10. That is take each column and scale values linearly so that the largest value is 10, and the smallest value in the column is 0. Round results to 2 decimal places. Call the result `y`

(Not required, but see if you can do the calculations in one line.)

Desired output: 

~~~
[[ 0.72  2.22  8.02]
 [ 8.87  8.33  5.68]
...
 [ 2.68  0.    3.58]
 [ 0.    1.   10.  ]]
 ~~~

In [262]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 30).reshape(10,3)

In [264]:
print(np.round(10 * (x - np.min(x, axis = 0)) / (np.max(x, axis = 0) - np.min(x, axis = 0)), 2))

[[ 0.72  2.22  8.02]
 [ 8.87  8.33  5.68]
 [ 0.93 10.    6.17]
 [10.    5.44  7.9 ]
 [10.    1.11  3.95]
 [ 2.37  1.22  7.16]
 [ 5.88  1.33  0.86]
 [ 9.48  9.11  0.  ]
 [ 2.68  0.    3.58]
 [ 0.    1.   10.  ]]


#### NP.9:

Task: Replace all NaN values in the matrix `x` with 0.

Desired output: 

~~~
[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
~~~

In [267]:
# do not modify
np.random.seed(100)
x = np.random.randint(100,size = 12).reshape(4,3).astype('float')
row = np.array([1, 2, 3])
col = np.array([2, 1, 0])
x[row, col] = np.nan

In [268]:
print(np.nan_to_num(x, nan = 0))

[[ 8. 24. 67.]
 [87. 79.  0.]
 [10.  0. 52.]
 [ 0. 53. 66.]]
